GET http://localhost:3000

### 
POST  http://localhost:3000/api/user/register 
Content-Type: application/json

{
    "email": "namsang09012s@gmail.com",
    "password": "s0902#@!zA"
}

###
POST  http://localhost:3000/api/user/login 
Content-Type: application/json

{
    "email": "namsang09012s@gmail.com",
    "password": "s0902#@!zA"
}

###
POST  http://localhost:3000/api/user/refresh-token 

###
POST  http://localhost:3000/api/user/logout 


